### PR TITLE
fix(gv-select): correctly display and place option list when used in a small container

### PR DESCRIPTION
**Pull request by gaetanmaisse**
**Issue**

https://gravitee.atlassian.net/browse/APIM-866
https://github.com/gravitee-io/issues/issues/8348

**Description**

Correctly display and place options list when used in a small container
Delegate option list placement to `popper.js` to ensure correct behaviour.

**Additional context**

Before
image

After
image

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-mwmvdfcmsr.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
Hey dear reviewer, I'm the Gravitee.io bot :robot:

I just want to tell you that `package.json` has been updated in this PR. 

Some components are based on third party libraries, for integration into a web component, we extract the css from its libraries as assets.

WARNING: When `highlight.js` or `github-markdown-css` are updated, we must run `yarn build` task to update the css.

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 4c0f498cd102e8402a2aeae8173970ad8ff18da8
</p>

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.38.9-fix-gv-select-4c0f498
```
or
```shell
yarn add @gravitee/ui-components@3.38.9-fix-gv-select-4c0f498
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.38.9-fix-gv-select-df2eaaa
```
or
```shell
yarn add @gravitee/ui-components@3.38.9-fix-gv-select-df2eaaa
```

**Review by ThibaudAV — APPROVED** [review]
🤞

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.38.9-fix-gv-select-871a30f
```
or
```shell
yarn add @gravitee/ui-components@3.38.9-fix-gv-select-871a30f
```

**Pull request merged**
