### PR TITLE
feat: bump asciidoctor to 3.0.2

### PR DESCRIPTION
**Pull request by ThibaudAV**
**Issue**

Needed for apim with Angular 14 and Angular CLI

**Description**

- [x] Tested with apim 3.20
- [x] Tested with apim master

**Additional context**

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-mbfnvdrhcg.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
Hey dear reviewer, I'm the Gravitee.io bot :robot:

I just want to tell you that `package.json` has been updated in this PR. 

Some components are based on third party libraries, for integration into a web component, we extract the css from its libraries as assets.

WARNING: When `highlight.js` or `github-markdown-css` are updated, we must run `yarn build` task to update the css.

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 88516a67eba4a0d04940c3ac5e8dfd78903245d3
</p>

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.44.0-bump-asciidoctor-88516a6
```
or
```shell
yarn add @gravitee/ui-components@3.44.0-bump-asciidoctor-88516a6
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.44.0-bump-asciidoctor-46365fa
```
or
```shell
yarn add @gravitee/ui-components@3.44.0-bump-asciidoctor-46365fa
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.44.0-bump-asciidoctor-6ab0b79
```
or
```shell
yarn add @gravitee/ui-components@3.44.0-bump-asciidoctor-6ab0b79
```

**Review by gaetanmaisse — APPROVED** [review]

**Review by loriepisicchio — APPROVED** [review]

**Pull request merged**
