### PR TITLE
Feat/6626 add conditional flow icon

### PR DESCRIPTION
**Pull request by marcambier**
**Issue**

https://github.com/gravitee-io/issues/issues/6626

**Description**

feat: add conditional flow icon

When a execution condition is defined on a flow,
The 'conditional' icon appears in the flows menu, and the flow title on top.
It uses the same icon as conditional policies.

**Additional context**

Also added a tooltip for the conditional icon on policy.

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-gbyqvqgukv.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.25.3-feat-6626-add-conditional-flow-icon-a305216
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.25.3-feat-6626-add-conditional-flow-icon-39e1fde
```

**Review by gaetanmaisse — APPROVED** [review]

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.26.0-feat-6626-add-conditional-flow-icon-d2e4276
```

**Pull request merged**
