### PR TITLE
add new gv-select-native component 

### PR DESCRIPTION
**Pull request by gcusnieux**
**Issue**

https://github.com/gravitee-io/gravitee-ui-components/issues/251
https://github.com/gravitee-io/gravitee-ui-components/issues/329
https://github.com/gravitee-io/issues/issues/6487

Sorry for the duplication...
I kept the `<gv-select>` to not create a breaking change and for the story `TransparentOnDarkBackground` which can't be reimplemented correctly with this new component.
Later, it would be nice to turn the `gv-select` into a `gv-listbox` or something like that, letting users build the list via the `slot`, this would allow better customization and data event binding possibilities.

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

**This is still experimental ⚠️**

To use it in your project run the following lines:
```shell
echo @gravitee-io:registry=https://npm.pkg.github.com > .npmrc
npm install @gravitee-io/ui-components@3.21.1-b014eb3
rm -rf node_modules/@gravitee
mv node_modules/@gravitee-io node_modules/@gravitee
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

**This is still experimental ⚠️**

To use it in your project run the following lines:
```shell
echo @gravitee-io:registry=https://npm.pkg.github.com > .npmrc
npm install @gravitee-io/ui-components@3.21.1-5aa92ce
rm -rf node_modules/@gravitee
mv node_modules/@gravitee-io node_modules/@gravitee
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

**This is still experimental ⚠️**

To use it in your project run the following lines:
```shell
echo @gravitee-io:registry=https://npm.pkg.github.com > .npmrc
npm install @gravitee-io/ui-components@3.21.3-8217140
rm -rf node_modules/@gravitee
mv node_modules/@gravitee-io node_modules/@gravitee
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

**This is still experimental ⚠️**

To use it in your project run the following lines:
```shell
echo @gravitee-io:registry=https://npm.pkg.github.com > .npmrc
npm install @gravitee-io/ui-components@3.21.6-28d32c1
rm -rf node_modules/@gravitee
mv node_modules/@gravitee-io node_modules/@gravitee
```

**Review by gaetanmaisse — APPROVED** [review]
The behaviour when the `multiple` attribute is selected matches the one from the HTML default select (https://www.w3schools.com/tags/att_select_multiple.asp) but is quite strange. We need to discuss that with the team. Otherwise it looks good 🚀

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

**This is still experimental ⚠️**

To use it in your project run the following lines:
```shell
echo @gravitee-io:registry=https://npm.pkg.github.com > .npmrc
npm install @gravitee-io/ui-components@3.21.7-4c7cf27
rm -rf node_modules/@gravitee
mv node_modules/@gravitee-io node_modules/@gravitee
```

**Pull request merged**
