### PR TITLE
feat: release directly at the root lvl and not inside dist folder

### PR DESCRIPTION
**Pull request by ThibaudAV**
**Issue**
na improve where i work

**Description**

Release directly with ./package.json and not with the copied one inside /dist
To make npm link work and to have licence + readme + changelog inside npm release package

**Additional context**

TOTO add into git commit message if reviewer say 🚀 

BRAKING CHANGE
import with `@gravitee/ui-components/src...` not work anymore 
ex to fix :
`import { deepEqual } from '@gravitee/ui-components/src/lib/utils';`
must be replaced by:
`import { deepEqual } from '@gravitee/ui-components';`

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-wgbzdcukwz.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
Hey dear reviewer, I'm the Gravitee.io bot :robot:

I just want to tell you that `package.json` has been updated in this PR. 

Some components are based on third party libraries, for integration into a web component, we extract the css from its libraries as assets.

WARNING: When `highlight.js` or `github-markdown-css` are updated, we must run `yarn build` task to update the css.

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 25d41567343d671196e69504c5242cc79e04e38d
</p>

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.27.2-chore-release-25d4156
```
or
```shell
yarn add @gravitee/ui-components@3.27.2-chore-release-25d4156
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.27.2-chore-release-9f040b5
```
or
```shell
yarn add @gravitee/ui-components@3.27.2-chore-release-9f040b5
```

**Comment by ThibaudAV** [comment]
sad hard to do without breaking changes

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.27.2-chore-release-4fe2a47
```
or
```shell
yarn add @gravitee/ui-components@3.27.2-chore-release-4fe2a47
```

**Pull request closed without merging**
