### PR TITLE
fix: remove confirm state when policy changed or submitted

### PR DESCRIPTION
**Pull request by gcusnieux**
**Issue**

https://gravitee.atlassian.net/browse/AM-1012

**Description**

A small description of what you did in that PR.

**Additional context**

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-jbwxqpjjya.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.45.0-am-1012-fix-policies-85bb328
```
or
```shell
yarn add @gravitee/ui-components@3.45.0-am-1012-fix-policies-85bb328
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.45.0-am-1012-fix-policies-44e48cc
```
or
```shell
yarn add @gravitee/ui-components@3.45.0-am-1012-fix-policies-44e48cc
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.45.0-am-1012-fix-policies-96b6e7a
```
or
```shell
yarn add @gravitee/ui-components@3.45.0-am-1012-fix-policies-96b6e7a
```

**Review by leleueri — APPROVED** [review]

**Pull request merged**
