### PR TITLE
Add license checker and remove Maven related files

### PR DESCRIPTION
**Pull request by gaetanmaisse**
**Issue**

Fixes https://github.com/gravitee-io/gravitee-ui-components/issues/295

**Description**

 - Added a lib to check license header is well applied to every file, it can be run with `npm run lint:license` and auto add missing one with `npm run lint:license:fix`
 - Added the license check in a CircleCI step
 - Removed everything related to Maven
 - Revert outdated commit lint rules as release commits are now compliant
 - Fix license field in `package.json`

### CODE REVIEW

**Review by aelamrani — COMMENTED** [review]
LGTM, nice job!

I am just wondering if we can add the new commands for license checking / generation in the readme?

**Comment by gaetanmaisse** [comment]
Sure, will do it! 
I was thinking to add it in a git pre-commit hook, as we did for prettier in Cockpit, to automatically run it and stop worrying about it 🤷🏻  What're your thoughts?

**Comment by aelamrani** [comment]
Good idea

**Review by jgiovaresco — APPROVED** [review]

**Pull request merged**
