### PR TITLE
feat: add icons for new AM flows

### PR DESCRIPTION
**Pull request by remisultan**
**Issue**

https://github.com/gravitee-io/issues/issues/7193

**Description**

This PR handles new icons for new AM flows.

**Additional context**

as discussed with @gaetanmaisse and @ThibaudAV some work will be done to handle `shape` in the flow schemas
in the future.

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-lglghnfmps.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.30.1-issues-7193-am-upgrade-policy-studio-db5c3fa
```
or
```shell
yarn add @gravitee/ui-components@3.30.1-issues-7193-am-upgrade-policy-studio-db5c3fa
```

**Review by ThibaudAV — APPROVED** [review]

**Review by ThibaudAV — APPROVED** [review]
maybe you could change some AM stories to display this icons 🤷‍♂️  
like others : 
image

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.30.1-issues-7193-am-upgrade-policy-studio-2bc172a
```
or
```shell
yarn add @gravitee/ui-components@3.30.1-issues-7193-am-upgrade-policy-studio-2bc172a
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.30.1-issues-7193-am-upgrade-policy-studio-225ba3f
```
or
```shell
yarn add @gravitee/ui-components@3.30.1-issues-7193-am-upgrade-policy-studio-225ba3f
```

**Comment by remisultan** [comment]
> maybe you could change some AM stories to display this icons 🤷‍♂️ like others : image

Done ;)

image

**Pull request merged**
