### PR TITLE
Add story to test resource-cache-redis with gv-schema-form

### PR DESCRIPTION
**Pull request by gcusnieux**
**Issue**

https://github.com/gravitee-io/issues/issues/7172

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-ymaiaoefsx.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.30.0-7172-fix-configuration-223a38d
```
or
```shell
yarn add @gravitee/ui-components@3.30.0-7172-fix-configuration-223a38d
```

**Comment by gaetanmaisse** [comment]
I think the 2nd commit should be a `fix` otherwise no release will be triggered when this PR will be merged

**Comment by gcusnieux** [comment]
> I think the 2nd commit should be a `fix` otherwise no release will be triggered when this PR will be merged

Yes, there is no fix, it is just to facilitate the test.
The fix is in here: https://github.com/gravitee-io/gravitee-resource-cache-redis/pull/17

**Comment by gaetanmaisse** [comment]
Yes... 🤦🏻 I just realized after posting my comment 😂

**Review by gaetanmaisse — APPROVED** [review]

**Pull request merged**
