### PR TITLE
CI: Check definition.json file

### PR DESCRIPTION
**Pull request by gaetanmaisse**

### CODE REVIEW

**Comment by graviteeio** [comment]
Wow it looks like this is a comment on a PR!

**Comment by graviteeio** [comment]
Wow it looks like this is a comment on a PR!

**Comment by graviteeio** [comment]
Wow it looks like this is a comment on a PR!

**Comment by graviteeio** [comment]
Wow it looks like this is a comment on a PR!

**Comment by graviteeio** [comment]
:robot: Hey! I'm the Gravitee.io bot. I just to tell you that 'definition.json' has been updated in this PR. As this file is used to theme clients' portals you should carefully review it to avoid regression as most as possible!

**Comment by graviteeio** [comment]
:robot:  Hey Dear Reviewer! I'm the Gravitee.io bot.
I just to tell you that 'definition.json' has been updated in this PR.
As this file is used to theme clients' portals you should carefully review it to avoid regression as most as possible!

**Comment by gaetanmaisse** [comment]
Closing in favour of https://github.com/gravitee-io/gravitee-ui-components/pull/414

**Pull request closed without merging**
