### PR TITLE
feat: add disabled state for gv-cron-editor

### PR DESCRIPTION
**Pull request by ThibaudAV**
**Issue**
To reuse it in apim 

**Description**
image

**Additional context**

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.36.1-cron-148e80a
```
or
```shell
yarn add @gravitee/ui-components@3.36.1-cron-148e80a
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.36.1-cron-2a46553
```
or
```shell
yarn add @gravitee/ui-components@3.36.1-cron-2a46553
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.36.1-cron-10cfcf8
```
or
```shell
yarn add @gravitee/ui-components@3.36.1-cron-10cfcf8
```

**Review by gcusnieux — APPROVED** [review]

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.36.1-cron-5e5435d
```
or
```shell
yarn add @gravitee/ui-components@3.36.1-cron-5e5435d
```

**Pull request merged**
