### PR TITLE
fix: schema.required is not a mandatory property

### PR DESCRIPTION
**Pull request by wbabyte**
**Issue**

https://gravitee.atlassian.net/browse/APIM-6736

**Description**

A small description of what you did in that PR.

**Additional context**

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-shmqepndnt.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@4.2.4-fix-schema-required-a25fe13
```
or
```shell
yarn add @gravitee/ui-components@4.2.4-fix-schema-required-a25fe13
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@4.2.4-fix-schema-required-15f5d66
```
or
```shell
yarn add @gravitee/ui-components@4.2.4-fix-schema-required-15f5d66
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@4.2.4-fix-schema-required-9fd1905
```
or
```shell
yarn add @gravitee/ui-components@4.2.4-fix-schema-required-9fd1905
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@4.2.4-fix-schema-required-4f2a8fa
```
or
```shell
yarn add @gravitee/ui-components@4.2.4-fix-schema-required-4f2a8fa
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@4.2.4-fix-schema-required-cc7e98d
```
or
```shell
yarn add @gravitee/ui-components@4.2.4-fix-schema-required-cc7e98d
```

**Review by ThibaudAV — APPROVED** [review]

**Pull request merged**
