### PR TITLE
Draft - Hands on Web-Types 

### PR DESCRIPTION
**Pull request by gaetanmaisse**
**Issue**

https://github.com/gravitee-io/gravitee-ui-components/issues/XXXXX

**Description**

A small description of what you did in that PR.

**Additional context**

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-sanweucmcb.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
Hey dear reviewer, I'm the Gravitee.io bot :robot:

I just want to tell you that `package.json` has been updated in this PR. 

Some components are based on third party libraries, for integration into a web component, we extract the css from its libraries as assets.

WARNING: When `highlight.js` or `github-markdown-css` are updated, we must run `yarn build` task to update the css.

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against bf042026a1b307852158bf8d8058a57bff52964f
</p>

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.28.5-add-webtypes-bf04202
```
or
```shell
yarn add @gravitee/ui-components@3.28.5-add-webtypes-bf04202
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.28.5-add-webtypes-71e5a9a
```
or
```shell
yarn add @gravitee/ui-components@3.28.5-add-webtypes-71e5a9a
```

**Comment by gaetanmaisse** [comment]
Closing the experiment

**Pull request closed without merging**
