### PR TITLE
fix: gv-select default background should be white

### PR DESCRIPTION
**Pull request by ytvnr**
Fixes https://github.com/gravitee-io/gravitee-ui-components/issues/284

### CODE REVIEW

**Review by gcusnieux — APPROVED** [review]

**Comment by gaetanmaisse** [comment]
It looks weird on a white background no? 
image

**Comment by ytvnr** [comment]
@gaetanmaisse indeed, thanks to chromatic I saw it :(

**Review by gaetanmaisse — APPROVED** [review]

**Review by gaetanmaisse — CHANGES_REQUESTED** [review]
It looks it doesn't work properly on the portal

**Comment by gcusnieux** [comment]
Same on master, but it looks like a a11y problem when a value has selected on "Simple on dark background" story.
Capture d’écran 2021-03-05 à 19 22 57

**Review by gaetanmaisse — APPROVED** [review]
🆗  On chromatic and cockpit side

**Pull request merged**
