### PR TITLE
Split policy settings into two sections 

### PR DESCRIPTION
**Pull request by ThibaudAV**
**Issue**
Linked to gravitee-io/issues#6614 https://github.com/gravitee-io/issues/issues/6615

**Description**

Split policy settings into two sections (Common, Policy) to be able to add conditional inside common section

**Additional context**
image

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.24.3-6614-conditional-policy-v2-07c065d
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.24.3-6614-conditional-policy-v2-ad8f05f
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.24.4-6614-conditional-policy-v2-7564e48
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.24.4-6614-conditional-policy-v2-ceda37c
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.24.4-6614-conditional-policy-v2-baddef2
```

**Review by ytvnr — APPROVED** [review]

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.24.5-6614-conditional-policy-v2-5e326c7
```

**Pull request merged**
