### PR TITLE
Add CommitLint with conventional commit config

### PR DESCRIPTION
**Pull request by gaetanmaisse**
**Issue**

Part of https://github.com/gravitee-io/gravitee-ui-components/issues/273

**Description**

The goal of this PR is to introduce CommitLint and use it to ensure the commits messages will be successfully parsed during the release (that will be based on semantic release). It is set up to check the commit both:
 - in the CI as part of the `lint-test` job
 - in a `commit-msg` hook locally to reject invalid commits directly

### CODE REVIEW

**Review by gcusnieux — APPROVED** [review]

**Comment by gcusnieux** [comment]
I think about it ... it would be cool to have the changelog below the "Welcome" page in the Documentation section. wdyt?

**Comment by gaetanmaisse** [comment]
Good idea! Doing it right now :)

**Comment by gaetanmaisse** [comment]
> Good idea! Doing it right now :)

Storybook doesn't look happy with displaying the changelog as it, I created an issue for further investigation: https://github.com/gravitee-io/gravitee-ui-components/issues/289

**Pull request merged**
