### PR TITLE
fix(gv-schema-form): wait browser refresh before update

### PR DESCRIPTION
**Pull request by gcusnieux**
gravitee-io/issues#6514

### CODE REVIEW

**Review by ytvnr — APPROVED** [review]

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

**This is still experimental ⚠️**

To use it in your project run the following lines:
```shell
echo @gravitee-io:registry=https://npm.pkg.github.com > .npmrc
npm install @gravitee-io/ui-components@3.21.3-e42375d
rm -rf node_modules/@gravitee
mv node_modules/@gravitee-io node_modules/@gravitee
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

**This is still experimental ⚠️**

To use it in your project run the following lines:
```shell
echo @gravitee-io:registry=https://npm.pkg.github.com > .npmrc
npm install @gravitee-io/ui-components@3.21.3-8a7768d
rm -rf node_modules/@gravitee
mv node_modules/@gravitee-io node_modules/@gravitee
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

**This is still experimental ⚠️**

To use it in your project run the following lines:
```shell
echo @gravitee-io:registry=https://npm.pkg.github.com > .npmrc
npm install @gravitee-io/ui-components@3.21.3-535f6f5
rm -rf node_modules/@gravitee
mv node_modules/@gravitee-io node_modules/@gravitee
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

**This is still experimental ⚠️**

To use it in your project run the following lines:
```shell
echo @gravitee-io:registry=https://npm.pkg.github.com > .npmrc
npm install @gravitee-io/ui-components@3.21.3-dbc0f49
rm -rf node_modules/@gravitee
mv node_modules/@gravitee-io node_modules/@gravitee
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

**This is still experimental ⚠️**

To use it in your project run the following lines:
```shell
echo @gravitee-io:registry=https://npm.pkg.github.com > .npmrc
npm install @gravitee-io/ui-components@3.21.4-2d2f5b7
rm -rf node_modules/@gravitee
mv node_modules/@gravitee-io node_modules/@gravitee
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

**This is still experimental ⚠️**

To use it in your project run the following lines:
```shell
echo @gravitee-io:registry=https://npm.pkg.github.com > .npmrc
npm install @gravitee-io/ui-components@3.21.4-7106b4e
rm -rf node_modules/@gravitee
mv node_modules/@gravitee-io node_modules/@gravitee
```

**Pull request merged**
