### PR TITLE
fix(gv-schema-form): remove useless compact attribute

### PR DESCRIPTION
**Pull request by gcusnieux**
Related to gravitee-io/issues#7022

See https://github.com/gravitee-io/gravitee-policy-data-logging-masking/pull/28 for 📸 screenshots

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-gdhvfjsrvl.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.31.0-7022-always-display-label-d9ae381
```
or
```shell
yarn add @gravitee/ui-components@3.31.0-7022-always-display-label-d9ae381
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.31.0-7022-always-display-label-f351b4d
```
or
```shell
yarn add @gravitee/ui-components@3.31.0-7022-always-display-label-f351b4d
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.31.1-7022-always-display-label-73a8200
```
or
```shell
yarn add @gravitee/ui-components@3.31.1-7022-always-display-label-73a8200
```

**Review by ytvnr — APPROVED** [review]
lgtm, but are we sure it is not used by other projects ?

**Comment by gcusnieux** [comment]
> lgtm, but are we sure it is not used by other projects ?

Yes

**Pull request merged**
