### PR TITLE
feat(policy-studio): fork gv-policy-studio to gv-design

### PR DESCRIPTION
**Pull request by gcusnieux**
gravitee-io/issues#6893

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-zgpkvglpdm.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.28.7-debug-mode-add-menu-ded8a59
```
or
```shell
yarn add @gravitee/ui-components@3.28.7-debug-mode-add-menu-ded8a59
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.28.7-debug-mode-add-menu-fd03e65
```
or
```shell
yarn add @gravitee/ui-components@3.28.7-debug-mode-add-menu-fd03e65
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.28.7-debug-mode-add-menu-8e89e8a
```
or
```shell
yarn add @gravitee/ui-components@3.28.7-debug-mode-add-menu-8e89e8a
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.28.7-debug-mode-add-menu-43d8764
```
or
```shell
yarn add @gravitee/ui-components@3.28.7-debug-mode-add-menu-43d8764
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.28.7-debug-mode-add-menu-0cd9ce2
```
or
```shell
yarn add @gravitee/ui-components@3.28.7-debug-mode-add-menu-0cd9ce2
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.28.7-debug-mode-add-menu-1e925ea
```
or
```shell
yarn add @gravitee/ui-components@3.28.7-debug-mode-add-menu-1e925ea
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.28.7-debug-mode-add-menu-32da1e0
```
or
```shell
yarn add @gravitee/ui-components@3.28.7-debug-mode-add-menu-32da1e0
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.28.7-debug-mode-add-menu-ae5ff63
```
or
```shell
yarn add @gravitee/ui-components@3.28.7-debug-mode-add-menu-ae5ff63
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.28.7-debug-mode-add-menu-80a0f3c
```
or
```shell
yarn add @gravitee/ui-components@3.28.7-debug-mode-add-menu-80a0f3c
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.28.7-debug-mode-add-menu-77fc93f
```
or
```shell
yarn add @gravitee/ui-components@3.28.7-debug-mode-add-menu-77fc93f
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.28.7-debug-mode-add-menu-b568d2c
```
or
```shell
yarn add @gravitee/ui-components@3.28.7-debug-mode-add-menu-b568d2c
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.28.7-debug-mode-add-menu-9d0c1b1
```
or
```shell
yarn add @gravitee/ui-components@3.28.7-debug-mode-add-menu-9d0c1b1
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.28.7-debug-mode-add-menu-e271dd2
```
or
```shell
yarn add @gravitee/ui-components@3.28.7-debug-mode-add-menu-e271dd2
```

**Review by ThibaudAV — APPROVED** [review]
LGTM, tested with storybook

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.28.8-debug-mode-add-menu-72c771a
```
or
```shell
yarn add @gravitee/ui-components@3.28.8-debug-mode-add-menu-72c771a
```

**Review by ThibaudAV — APPROVED** [review]

**Pull request merged**
