### PR TITLE
🎳. Groupe component, stories and test into dedicated folder

### PR DESCRIPTION
**Pull request by ThibaudAV**
**Issue**

na 

**Description**
Groupe component, stories and test into dedicated folder

**Additional context**

For apim : https://github.com/gravitee-io/gravitee-api-management/pull/1036

Test by @ThibaudAV run app and open some screen and console :

- [x] APIM Console
- [x] APIM Portal

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-dvdhaeivrc.chromatic.com)

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-ubmjbfijhj.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
Hey dear reviewer, I'm the Gravitee.io bot :robot:

I just want to tell you that `package.json` has been updated in this PR. 

Some components are based on third party libraries, for integration into a web component, we extract the css from its libraries as assets.

WARNING: When `highlight.js` or `github-markdown-css` are updated, we must run `yarn build` task to update the css.

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7f69b9fd3c8e6227deb2bb0f15ff3e4ce7ee598d
</p>

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.27.0-grp-compo-stories-test-52da78a
```
or
```shell
yarn add @gravitee/ui-components@3.27.0-grp-compo-stories-test-52da78a
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.27.0-grp-compo-stories-test-05684ca
```
or
```shell
yarn add @gravitee/ui-components@3.27.0-grp-compo-stories-test-05684ca
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.27.0-grp-compo-stories-test-db29746
```
or
```shell
yarn add @gravitee/ui-components@3.27.0-grp-compo-stories-test-db29746
```

**Review by gcusnieux — APPROVED** [review]

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.27.0-grp-compo-stories-test-0523cb2
```
or
```shell
yarn add @gravitee/ui-components@3.27.0-grp-compo-stories-test-0523cb2
```

**Pull request merged**
