### PR TITLE
Sanitize Asciidoc content to avoid XSS attacks

### PR DESCRIPTION
**Pull request by gaetanmaisse**
**Issue**

https://gravitee.atlassian.net/browse/APIM-2011

**Description**

Sanitize Asciidoc content to avoid XSS attacks

To test: Go to the dedicated story `organisms > gv-documentation > sanitized-malicious-doc` -> Tada no more Alert displayed by the browser

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://5ffff84833d7150021078521-swnkhhzuql.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
Hey dear reviewer, I'm the Gravitee.io bot :robot:

I just want to tell you that `package.json` has been updated in this PR. 

Some components are based on third party libraries, for integration into a web component, we extract the css from its libraries as assets.

WARNING: When `highlight.js` or `github-markdown-css` are updated, we must run `yarn build` task to update the css.

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 4004b2ae3deafa272351248ca1146b7e9f5447e6
</p>

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.41.0-apim-2011-sanitize-asciidoc-4004b2a
```
or
```shell
yarn add @gravitee/ui-components@3.41.0-apim-2011-sanitize-asciidoc-4004b2a
```

**Comment by gaetanmaisse** [comment]
-> New story: https://5ffff84833d7150021078521-drhmxskkrh.chromatic.com/?path=/story/organisms-gv-documentation--sanitized-malicious-doc

**Review by ThibaudAV — APPROVED** [review]

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A beta version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-components@3.41.0-apim-2011-sanitize-asciidoc-6f798fe
```
or
```shell
yarn add @gravitee/ui-components@3.41.0-apim-2011-sanitize-asciidoc-6f798fe
```

**Pull request merged**
